spring:
  application:
    name: dog-service
    org: petclinic
  datasource:
    url: "jdbc:postgresql://localhost:5432/dog-db"
    username: "dog"
    password: "woof"
  jpa:
    open-in-view: false
  jmx:
    enabled: false
  mvc:
    problemdetails:
      enabled: true
  sql:
    init:
      mode: always

server:
  error:
    include-message: always

management:
#  observations:
#    http:
#      server:
#        requests:
#          name: "http.server.in"
  endpoints:
    web:
      exposure:
        include:
        - "*"
    jmx:
      exposure:
        include:
        - "*"
  endpoint:
    env:
      show-values: always
  metrics:
    tags:
      application: ${spring.application.name}
      org: ${spring.application.org}
    distribution:
      percentiles-histogram:
        # all: true
        http.server.requests: true
  tracing:
    sampling:
      probability: 1.0
  info:
    java:
      enabled: true
    os:
      enabled: true

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG

jdbc:
  datasource-proxy:
    include-parameter-values: true
    query:
      enable-logging: true
      log-level: INFO

application:
  security:
    users:
    - name: "user"
      password: "password"
    - name: "admin"
      password: "secret"
      roles: ["admin"]
